### ISSUE TITLE
P-table with virtual scroll and filter does not have responsive height

### ISSUE THREAD

**Issue by IreneTepe** [primefaces/primeng#13425]
### Describe the bug

I have a p-table with virtual scroll and into the caption a search input. 
Sometimes, when i search for a specific item into the table via search (e.g get 2 results) and then clear the search , the scroll height does not change to the initial one. ( It keeps the height of the previous result). 
This also occurs when i resize the browser window and the table change width and height.
Somehow the scrollHeight remains to the previous value.

**Troubleshoot steps:**

-  If i remove the virtual scroll the scrollHeight is responsive even if i resize the window and filter persons several times (but we need virtual scroll in our implementation)

- If i keep the virtual scroll and change the scrollHeight to 'flex' with a set up height to parent element, things works as expected (but the height of the parent element is not responsive as i expected - in case of one element we see a large empty table and it gets tricky to solve that issue which leads to more bugs)

### Environment

Angular CLI: 15.1.4
Node: 18.14.0
Package Manager: npm 9.3.1
OS: darwin x64

### Angular version

15.2.0

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.14.0

### Browser(s)

Chrome, Firefox, Safari

### Steps to reproduce the behavior

Lets say we have 10 results
1. filter table by value (e.g returns 5 results)
2. clear filter
3. We see only the 5/10 results

### Expected behavior

I expect that when we have a p-table with virtual scroll and the flexibility of searching things into in , the scroll height is responsive all the time according to our search.

**Comment by Crikey-Mikey** [comment]
Updating to 15.4.1 fixed the issue for me

**Comment by IreneTepe** [comment]
@Crikey-Mikey thank you for the feedback! I can not find something relevant on https://github.com/primefaces/primeng/blob/master/CHANGELOG.md#1541-2023-04-21 but these days i will upgrade the PrimeNg , so i will check that :)

**Comment by IreneTepe** [comment]
**Update:**
I had to upgrade to PrimeNg v16.1.0 and i still have the same problem. It is not solved.
Angular v16.1.0 and PrimeNg v16.1.0

**Comment by johanneszelger** [comment]
I can confirm this still exists in 17.3.1

**Comment by johanneszelger** [comment]
This can be fixed by calling 

dt.scroller.elementViewChild.nativeElement.style.height ='yourscrollheight'; 

after a filter is applied. However you will see a short flash of the wrong height unfortunately due to the change detection happening before.

**Comment by rghv932** [comment]
@johanneszelger can u pls help understand whats this dt?
I have p-table element used how can I define dt?

**Comment by aissadevlab** [comment]
I fixed by this line 

`this.dt.scroller.scrollHeight ='78vh'`

**Comment by petogriac** [comment]
confirming this is still an issue in 17.18.11

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by kinan66** [comment]
I am still getting this issue, even after upgrading to PrimeNg v19. For info I am using an object signal to pass the data values to the table.

**Comment by IreneTepe** [comment]
Hello @mertsincan , 

We did the upgrade to PrimeNg v19 and the problem persist. If we have the virtual scroll enabled and the search function active  the table is still not responsive.
 
**How to reproduce?**
1. make your window short (small height)
2. load the table and make any kind of query to the search input
3. make your window larger (or full size) again
the elements will stay the size they had when the page initially loaded

Shall I open a separate ticket for that?

Kind regards,
Irene

**Comment by panos1998** [comment]
Hello, I ran also to this issue, angular 19 primeng 19.0.9. The correct behaviour would be to dynamically adjust viewport height of the scrollarea according to the number of the rows. Also scrollHeight="flex" shrinks the height to 0px. @IreneTepe  maybe try to set the scrollHeight dynamicaly according to current number of rows, e.g you need to adjust height for 2 items, then set [scrollHeight]="2*itemSize" the only thing to determine is the current number of items. I will give it a try

**Comment by panos1998** [comment]
Yep that's it i will give you the code

**Comment by panos1998** [comment]
<----------------------------------------------------HTML----------------------------------------------------------------------->
<p-table #dt [paginator]="false" stripedRows [value]="data" [columns]="selectedColumns" dataKey="id"
      ###   **[scrollable]="true" [scrollHeight]="dynamicScrollHeight" [virtualScroll]="true" [virtualScrollItemSize]="65"** 
        paginatorDropdownAppendTo="body" [tableStyle]="{ 'overflow-x': 'hidden','padding-bottom':'65px' }"
        class="w-full table table-sm pb-5" [rowTrackBy]="trackItem" (onFilter)="trackRows($event)"> 
        <ng-template pTemplate="caption">

<----------------------------------------------------HTML----------------------------------------------------------------------------->

<-------------------------------------------Component.ts----------------------------------------------------------------------------->

OnInit{
dynamicScrollHeight:string = '400px';
}
  trackRows(event: any): void {
    console.log("filter applied") // 
    console.log(event) // Use a unique identifier or index for tracking
    this.dynamicScrollHeight= event.filteredValue.length*65 + 'px'; // Adjust the height based on the number of rows
    console.log(this.dynamicScrollHeight)
  }
<-----------------------------------------------------------Component.ts------------------------------------------------------------------->

**Comment by IreneTepe** [comment]
Hello @panos1998 !
Thanks a lot! I will give it a try.

**Comment by panos1998** [comment]
A small fix, to not overcome the maximum height, just set 400 if dynamicScrollHeight exceeds it

```
  trackRows(event: any): void {
    console.log("filter applied") // 
    console.log(event) // Use a unique identifier or index for tracking
    let maxHeight = 400
  ###   this.dynamicScrollHeight= event.filteredValue.length*65 > maxHeight? maxHeight + 'px' : event.filteredValue.length*65 + 'px'; // Adjust the height based on the number of rows
    console.log(this.dynamicScrollHeight)
  }
```
