### ISSUE TITLE
p-menu: Cannot read properties of undefined (reading 'getAttribute')

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#13638]
### Describe the bug

I do not have a repro for this, but it is occuring when we use a "popup" `<p-menu>` component.

The call stack is:

> main.js:155483 TypeError: Cannot read properties of undefined (reading 'getAttribute')
>     at _Menu.changeFocusedOptionIndex (primeng-menu.mjs:907:60)
>     at _Menu.onListBlur (primeng-menu.mjs:823:10)
>     at Menu_div_0_Template_ul_blur_2_listener (primeng-menu.mjs:375:37)
>     at executeListenerWithErrorHandling (core.mjs:16195:16)

The line causing the issue is in primeng-menu.mjs:

`order > -1 && this.focusedOptionIndex.set(links[order].getAttribute('id'));`

![image](https://github.com/primefaces/primeng/assets/18640860/bdecf925-d7ff-43a5-9f8a-373b94ccf86f)

Component defined as:

`<p-menu #menu [model]="items" [popup]="true"></p-menu>`

We show it on a <button> click:

`<button (click)="menu.toggle($event)">`

### Environment

Angular 16.2.2
PrimeNG 16.3.1

### Angular version

16.2.2

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

1. <p-menu #menu [model]="items" [popup]="true"></p-menu>
2. <button (click)="menu.toggle($event)">

### Expected behavior

No error.

**Comment by SoyDiego** [comment]
Hi @psarno. 
I have the same result as https://github.com/primefaces/primeng/issues/13636. I cannot replicate your problem.

## My Code

![image](https://github.com/primefaces/primeng/assets/19764334/ed3605c1-3377-47a1-a1ee-7194a0d30ad2)

![image](https://github.com/primefaces/primeng/assets/19764334/a1e6273d-3ae4-4b3c-a1cd-e00a2c91b4dc)

## Testing

![testing menu](https://github.com/primefaces/primeng/assets/19764334/3697ff37-6180-40a9-be4b-31a7b1943793)

**Comment by dalenguyen** [comment]
I think it was fixed in https://github.com/primefaces/primeng/pull/13585

**Comment by psarno** [comment]
@dalenguyen That does seem to be a fix for this.  #13568 that the PR fixes looks like the same report and has a repro.

This was merged, but apparently wasn't released as part of PrimeNG 16.3.1.  We're still seeing it.

**Comment by coneillpj** [comment]
> I think it was fixed in #13585

I don't think the fix has been released yet. The updated code doesn't seem to be in the `16.3.1` version of the package. https://www.npmjs.com/package/primeng?activeTab=versions shows that `16.3.1` was published 14 days ago (8/31/23). 
<img width="784" alt="image" src="https://github.com/primefaces/primeng/assets/70150841/c74928ab-6370-4b6b-b492-004d43537560">


The merge request that contained the fix was merged in 10 days ago (9/3/23)...

https://github.com/primefaces/primeng/activity?activity_type=pr_merge&actor=mertsincan
<img width="1320" alt="image" src="https://github.com/primefaces/primeng/assets/70150841/4a3a0d3e-a432-4d9c-8d8a-2434dd74cac5">

**Comment by psarno** [comment]
Can confirm not released yet, we are on the latest 16.3.1 and seeing this still.

It looks like it will go out with the next update.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
