### ISSUE TITLE
Overlay Panel: Interaction with components inside panel template cause panel to hide

### ISSUE THREAD

**Issue by simoneraffaelli** [primefaces/primeng#14323]
### Describe the bug

If I deselect a value from a dropdown or a checkbox the panel hides

### Environment

PrimeNG@16.9.1
Angular@16.2.0

### Reproducer

https://stackblitz.com/edit/gd88qz?file=src%2Fapp%2Fdemo%2Foverlay-panel-basic-demo.html

### Angular version

16.2.0

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Chrome, Firefox

### Steps to reproduce the behavior

1. Click on Show button to open the panel
2. Select and deselect the checkbox or a value inside the dropdown

### Expected behavior

Well I expect the panel to close only if I click outside the panel itself, I click the close icon or i press the esc button on my keyboard

**Comment by simoneraffaelli** [comment]
I think is the same as : https://github.com/primefaces/primeng/issues/14177

**Comment by roman-balzer** [comment]
https://github.com/primefaces/primeng/issues/14120#issuecomment-1834445793 for those that search a workaround

**Comment by simoneraffaelli** [comment]
Well that is not properly a workaround as you don't have the possibility to dismiss the panel by clicking outside of it.... I made some trials and I ended up using event.stopPropagation that in my case I think is the best solution (waiting for a proper bugfix by primeng team).
Here's the stackblitz: https://stackblitz.com/edit/gd88qz-t1zpxd?file=src%2Fapp%2Fdemo%2Foverlay-panel-basic-demo.html
(see the onChangeMethods)

**Comment by simoneraffaelli** [comment]
This problem is still present if you click the clear icon to clear the selection, you can check in the original stack blitz updating primeng version

**Comment by basvandenberg** [comment]
Same issue here, with a dropdown in a overlay-panel with `appendTo="body"`, clicking the clear icon in the dropdown closes the overlay panel. Would be great if this could be fixed.

**Comment by anlampe** [comment]
A fix was merged and is part of v17.0.1, please have a look: https://stackblitz.com/edit/gd88qz-r9ujpp?file=package.json.

**Comment by simoneraffaelli** [comment]
Yesterday I updated primeng version to 17.1.0 on my stackblitz and the problem was still there, but maybe I forgot to run npm i or idk what happend, because, as shown by @anlampe [here](https://github.com/primefaces/primeng/issues/14323#issuecomment-1857430580), I tried again today and actually the clear and the checkbox seems to be working now. The dropdowns with appendTo="body" are still broken though

**Comment by basvandenberg** [comment]
@anlampe I tried the demo that you created on stackblitz and both clicking the checkbox and the clear button indeed work, the overlay remains open, that's great. However, the overlay panel still closes when you select an option in the dropdown.

**Comment by anlampe** [comment]
Yes, I could reproduce it. Unfortunately, my PR was already 2 months old, when it was merged and it seems there was another conflicting change in the meantime. I'll have another look as soon as I've some free time.
