### ISSUE TITLE
<p-toast> is not working globally.

### ISSUE THREAD

**Issue by tayyabroy786** [primefaces/primeng#14422]
### Describe the bug

I have multiple modules with components. I have included the toaster in the shared module and am using it in the required modules. However, the issue I am facing is that I want to set the HTML <p-toast></p-toast> globally in app.component.html or layout.component.html. Additionally, I want it to work in sub-components without having to add it to each sub-component's HTML file. Why do I need to add this to all 100 components?

### Environment

Environment Information
Angular Version: [e.g., 16.1.0]
PrimeNG Version: [e.g., 16.0.2]
Browser(s): [e.g., Chrome, Firefox]
Operating System: [e.g., Windows 10]

### Angular version

16.1.0

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16

### Browser(s)

All

### Steps to reproduce the behavior

You have multiple modules, each containing components. The toaster component is included in a shared module and is being utilized in the required modules. However, you are encountering an issue where you want to globally set the HTML <p-toast></p-toast> in either app.component.html or layout.component.html. Additionally, you desire this global setting to automatically apply to sub-components without having to add it individually to each sub-component's HTML file. This becomes particularly cumbersome when dealing with a large number of components (in your example, 100 components), and you are questioning the necessity of manually adding this code to each one.

**Comment by cetincakiroglu** [comment]
Hi, 

Could you please share a stackblitz example so we can identify the issue?

**Comment by tayyabroy786** [comment]
okay
I have updated the code.
I have multiple modules, so I want Toaster to inject from shareModule using
the service file as you can see in example code.

01 - Toaster not showing.
02 - <p-toast></p-toast> (I want to use this only in one html no all
component HTML Files)
03 - Can you please make this example working, usin share module in all
module and we can only call this <p-toast></p-toast> app.component.html

Thanks

**Comment by cetincakiroglu** [comment]
You don't need to add it to 100 places, just create a shared module or import at the top level.

1- import toast module to the top level module
2- add `<p-toast></p-toast>` at the top level component where the router outlet located.
3- use message service to display the toast.

It should be something like that: 

```
<p-toast></p-toast>
<router-outlet></router-outlet>
```

**Comment by tayyabroy786** [comment]
No,
This is not working for me.
Please check example code, I have set all code using shared Module.
Link  -
https://stackblitz.com/edit/github-mv9zck

**Comment by yvkevitch** [comment]
I've encountered the same problem in angular 17 (standalone app).
You simply need to provide MessageService at the application level and not at the component level.

**Comment by Fourat-Khelifi** [comment]
@yvkevitch would you please explain more.
I tried but it's still the same.

**Comment by yvkevitch** [comment]
@Fourat-Khelifi  
Add a p-toast component to the root page of your app (eg in you app component)
Add the MessageService to the providers of your app.config.ts file
In the components where you want to use toasts, inject MessageService (Don't add it to the providers of these components)
This way it should work like a charm

**Comment by reidecarvalho** [comment]
There's still a problem. Capturing the error globally with ErrorHandler and calling MessageService on it, Toast does not appear, only if I click on the screen.

```
import { ErrorHandler, Injectable, inject } from '@angular/core';
import { AppMessageService } from './services/app-message.service';

@Injectable()
export class GlobalErrorHandler implements ErrorHandler {
  appMessageService = inject(AppMessageService);

  handleError(error: any): void {
    console.error('GlobalErrorHandler', error);

    this.appMessageService.error(
      `Erro processando solicitação:\n${error.message}`,
    );
  }
}
```

```
import { Injectable, inject } from '@angular/core';
import { MessageService } from 'primeng/api';

@Injectable({
  providedIn: 'root',
})
export class AppMessageService {
  private messageService = inject(MessageService);

  success(message: string): void {
    this.messageService.add({
      severity: 'success',
      summary: 'Sucesso',
      detail: message,
    });
  }

  info(message: string): void {
    this.messageService.add({
      severity: 'info',
      summary: 'Informação',
      detail: message,
    });
  }

  warn(message: string): void {
    this.messageService.add({
      severity: 'warn',
      summary: 'Atenção',
      detail: message,
    });
  }

  error(message: string): void {
    this.messageService.add({
      severity: 'error',
      summary: 'Erro',
      detail: message,
    });
  }
}

```

**Comment by emiliano-arango-nz** [comment]
Hi @reidecarvalho same issue here and I think it’s related to the ChangeDetectionStrategy for the toast component, which is using OnPush, so maybe a temp fix could be to force the change detection using:

**constructor(private ref: ChangeDetectorRef) {}** in your AppMessageService

and then:

**this.ref.detectChanges();**  in every method, for example:

error(message: string): void {
    this.messageService.add({
      severity: 'error',
      summary: 'Erro',
      detail: message,
    });
    this.ref.detectChanges(); 
  }

**Comment by pouyababaie** [comment]
@emiliano-arango-nz i guess that is not a very good practice. what if there was a global layout.service and the changeDetectionRef is not available in that service? is there another way that you tried and worked?

having the same issue here.
I'm using modules instead of stand-alone components. like the old version of angular applications.

i have provided the `MessageService` in my shared module but still , it wont work. also if there was a key assigned to the toast , the toast is shown twice for each trigger.

**Comment by filiptrivan** [comment]
> Hi [@reidecarvalho](https://github.com/reidecarvalho) same issue here and I think it’s related to the ChangeDetectionStrategy for the toast component, which is using OnPush, so maybe a temp fix could be to force the change detection using:
> 
> **constructor(private ref: ChangeDetectorRef) {}** in your AppMessageService
> 
> and then:
> 
> **this.ref.detectChanges();** in every method, for example:
> 
> error(message: string): void { this.messageService.add({ severity: 'error', summary: 'Erro', detail: message, }); this.ref.detectChanges(); }

@emiliano-arango-nz ChangeDetectorRef can't be used in services DI.

**Comment by pouyababaie** [comment]
@cetincakiroglu can you reopen this issue? i found out the problem was and is still with change-detection strategy being OnPush. is this service getting an update in future to use signals or rxjs instead of pure declarative code?

**Comment by finventario** [comment]
> [@Fourat-Khelifi](https://github.com/Fourat-Khelifi) Add a p-toast component to the root page of your app (eg in you app component) Add the MessageService to the providers of your app.config.ts file In the components where you want to use toasts, inject MessageService (Don't add it to the providers of these components) This way it should work like a charm

Thanks! I had MessageService in providers of my components, which was the cause of this issue in my case!
