### ISSUE TITLE
Cannot find module '@primeuix/styled' from 'node_modules/primeng/fesm2022/primeng-themes.mjs'

### ISSUE THREAD

**Issue by ratsey** [primefaces/primeng#16353]
### Describe the bug

Recognising that I'm using ^18.0.0-beta.1, although my code is running fine with the new themeing architecture, my tests are failing. I see that I do have @primeuix/styled in my node_modules, so do I need to somehow boostrap the theming in the same way that I do now in the app.component.ts with PrimeNGConfig?

```
    Cannot find module '@primeuix/styled' from 'node_modules/primeng/fesm2022/primeng-themes.mjs'

    Require stack:
      node_modules/primeng/fesm2022/primeng-themes.mjs
      node_modules/primeng/fesm2022/primeng-base.mjs
      node_modules/primeng/fesm2022/primeng-api.mjs
      node_modules/primeng/fesm2022/primeng-card.mjs
      projects/portal-common/src/components/hero/hero.component.ts
      projects/portal-common/src/components/hero/hero.component.spec.ts

      1 | import { CommonModule } from '@angular/common';
      2 | import { Component, computed, input, Signal } from '@angular/core';
    > 3 | import { CardModule } from 'primeng/card';
        | ^
      4 |
      5 | @Component({
      6 |   selector: 'lib-hero',

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (node_modules/primeng/fesm2022/primeng-themes.mjs:1:15)
      at Object.<anonymous> (node_modules/primeng/fesm2022/primeng-base.mjs:3:27)
      at Object.<anonymous> (node_modules/primeng/fesm2022/primeng-api.mjs:6:27)
      at Object.<anonymous> (node_modules/primeng/fesm2022/primeng-card.mjs:5:61)
      at Object.<anonymous> (projects/portal-common/src/components/hero/hero.component.ts:3:1)
      at Object.<anonymous> (projects/portal-common/src/components/hero/hero.component.spec.ts:3:1)
```

### Environment

```
Angular CLI: 18.1.4
Node: 20.16.0
Package Manager: npm 10.8.1
OS: win32 x64

Angular: 18.2.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server 
... router, ssr

Package                         Version
---------------------------------------------------------       
@angular-devkit/architect       0.1801.4
@angular-devkit/build-angular   18.1.4
@angular-devkit/core            18.2.3
@angular-devkit/schematics      18.2.3
@angular/cli                    18.1.4
@schematics/angular             18.1.4
ng-packagr                      18.2.1
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

Angular build is downgraded whilst waiting for a [federated modules fix](https://github.com/angular-architects/module-federation-plugin/issues/621) 

### Angular version

18.1.4

### PrimeNG version

18.0.0-beta.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.16.0

### Browser(s)

Edge 128.0.2739.63 (Official build) (64-bit)

#### Component Template

``` html
<div
  class="flex flex-column h-full w-full border-round gap-5 justify-content-between flex-wrap cursor-pointer"
  (click)="gotoLink()"
  [ngClass]="backgroundColor()"
  (keypress)="gotoLink()"
  tabindex="-1"
>
  <div
    class="flex-grow-1 bg-cover bg-center border-round-top"
    [style.background-image]="'url(' + imagePath() + ')'"
  ></div>
  <div class="flex-grow-1 p-0 m-0" [class]="fontColour()">
    <div test_id="title" class="font-semibold text-xl m-3">{{ title() }}</div>
    <div class="m-3 text-sm line-height-4">{{ message() }}</div>
  </div>
</div>
```

#### Component Code
``` typescript

import { CommonModule } from '@angular/common';
import { Component, computed, input, Signal } from '@angular/core';
import { CardModule } from 'primeng/card';

@Component({
  selector: 'lib-hero',
  standalone: true,
  imports: [CommonModule, CardModule],
  templateUrl: './hero.component.html',
  styleUrl: './hero.component.css',
})
export class HeroComponent {
  title = input<string>();
  link = input<string>();
  imagePath = input<string>();
  message = input<string>();
  backgroundColor = input<string>();

  // This computed signal could be improved upon by checking the alpha value of the background colour
  fontColour: Signal<string> = computed(() => {
    return this.backgroundColor()!.toString().includes('white')
      ? 'text-black'
      : 'text-white';
  });

  gotoLink() {
    window.open(this.link(), '_blank');
  }
}
```

#### Component Test
``` typescript
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { MockRender } from 'ng-mocks';
import { HeroComponent } from './hero.component';

describe('HeroComponent', () => {
  let component: HeroComponent;
  let fixture: ComponentFixture<HeroComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({}).compileComponents();

    fixture = MockRender(HeroComponent);
    component = fixture.componentInstance;

    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('should have a defined title', () => {
    expect(component.title).toBeDefined();
  });
});
```

#### Actual Test Output
```
  ● Test suite failed to run

    Cannot find module '@primeuix/styled' from 'node_modules/primeng/fesm2022/primeng-themes.mjs'

    Require stack:
      node_modules/primeng/fesm2022/primeng-themes.mjs
      node_modules/primeng/fesm2022/primeng-base.mjs
      node_modules/primeng/fesm2022/primeng-api.mjs
      node_modules/primeng/fesm2022/primeng-card.mjs
      projects/portal-common/src/components/hero/hero.component.ts
      projects/portal-common/src/components/hero/hero.component.spec.ts

      1 | import { CommonModule } from '@angular/common';
      2 | import { Component, computed, input, Signal } from '@angular/core';
    > 3 | import { CardModule } from 'primeng/card';
        | ^
      4 |
      5 | @Component({
      6 |   selector: 'lib-hero',

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (node_modules/primeng/fesm2022/primeng-themes.mjs:1:15)
      at Object.<anonymous> (node_modules/primeng/fesm2022/primeng-base.mjs:3:27)
      at Object.<anonymous> (node_modules/primeng/fesm2022/primeng-api.mjs:6:27)
      at Object.<anonymous> (node_modules/primeng/fesm2022/primeng-card.mjs:5:61)
      at Object.<anonymous> (projects/portal-common/src/components/hero/hero.component.ts:3:1)
      at Object.<anonymous> (projects/portal-common/src/components/hero/hero.component.spec.ts:3:1)
```

### Expected behavior

Tests run without exception

**Comment by cagataycivici** [comment]
This should have been installed transitively, we'll review, thank you.

**Comment by ratsey** [comment]
It's only in my tests that it's failing, the app runs just fine. Plus it's
there in my node modules folder so no idea why it doesn't see it.

**Comment by mertsincan** [comment]
Interesting! Can you share a repo that includes your config? Thanks,

**Comment by ratsey** [comment]
Update. I'm digging through the jest-resolve package to try to focus in on the issue. Not sure how much help this is, but the Jest function `findNodeModule` in `jest-resolve/build/resolver.js` is throwing this error:

``` 
Error: No known conditions for "." specifier in "@primeuix/styled" package
```

 I will update this post as I find more.

**Comment by ratsey** [comment]
@cagataycivici Have you been able to replicate this one? My 'fix' works for me but isn't a valid approach since my gitlab pipelines are failing the testing since they are doing a clean node-modules install.

**Comment by ratsey** [comment]
Far from my area of expertise so forgive my naivete.  This appears to be a CommonJS vs ESM - Jest has only experimental support for ESM. I'm trying to find the Jest settings for it, but adding 'require' or 'default' values to the PrimeNG export settings is resolving the issue. It doesn't look like support for CommonJS was dropped so I'm still at a loss as to why this just stopped working.

**Comment by rpastro** [comment]
@ratsey   I just started porting my app to PrimeNG v18 and I had the same issue. I was able to fix the tests by making the following changes to my jest.config.ts file.  I hope this helps you.

1) Add @primeuix/styled and @primeuix/utils to the esModules list in `transformIgnoreModules` parameter.
2) Add the location of the @primeuix packages in the `moduleNameMapper` parameter.


```
const esModules: string = [
  '@angular',
  '@ngrx',
  '@ngx-translate',
  '@primeuix/styled',
  '@primeuix/utils',
  'gridstack',
  'jquery',
  'lodash-es',
  'ngx-infinite-scroll',
  'primeng',
  'uuid'
].join('|');

const config: Config = {

...

  // A map from regular expressions to module names or to arrays of module names that allow to stub out resources with a single module
  moduleNameMapper: {
    '\\.(css|less)$': '<rootDir>/test/__mocks__/style-mock.ts',
    '@/environments/(.*)': '<rootDir>/src/environments/$1',
    '@/lib/(.*)': '<rootDir>/src/lib/$1',
    '@/(.*)': '<rootDir>/src/app/$1',
    '@primeuix/styled': '<rootDir>/node_modules/@primeuix/styled/index.mjs',
    '@primeuix/utils/(.*)': '<rootDir>/node_modules/@primeuix/utils/$1/index.mjs',
    'gridstack-angular': '<rootDir>/node_modules/gridstack/dist/angular/esm2020/gridstack-angular.mjs',
  },

...

  // An array of regexp pattern strings that are matched against all source file paths, matched files will skip transformation
  transformIgnorePatterns: [`<rootDir>/node_modules/(?!${esModules})`]

...

};

export default config;
```

**Comment by mertsincan** [comment]
Thanks a lot @ratsey, Fixed in primeuix v0.1.2.

**Comment by jogerj** [comment]
@mertsincan the primeng repo still needs to update the dependency to use 0.1.2 tho

**Comment by cetincakiroglu** [comment]
Fixed in 18.0.0-beta.2 https://github.com/primefaces/primeng/commit/76a86f93d636fb28290cb3979a5d9095cb5235d2

**Comment by jogerj** [comment]
https://www.npmjs.com/package/primeng/v/18.0.0-beta.2?activeTab=code

was the correct branch published? the published package still depends on 0.0.6 :(

**Comment by clude86** [comment]
Is it possible that this bug was fixed in PrimeNG 18, but not in PrimeNG 19.0.9? In PrimeNG 19.0.9 sill use @primeuix/styled version 0.3.2.

**Comment by chocoboeve** [comment]
> Is it possible that this bug was fixed in PrimeNG 18, but not in PrimeNG 19.0.9? In PrimeNG 19.0.9 @primeuix/styled version 0.3.2.
> 
> Error:
> 
> [ERROR] TS2307: Cannot find module '@primeuix/utils/eventbus' or its corresponding type declarations. [plugin angular-compiler]
> 
> ```
> node_modules/@primeuix/styled/index.d.mts:1:42:
>   1 │ import * as _primeuix_utils_eventbus from '@primeuix/utils/eventbus';
> ```

Got the same issue.

**Comment by cheesgno** [comment]
The same for me

**Comment by JEBSCS** [comment]
I have the same issue but in PrimeNG 19.0.8 and @primeng/themes 19.0.8 I am not having this issue.

**Comment by cheesgno** [comment]
> I have the same issue but in PrimeNG 19.0.8 and @primeng/themes 19.0.8 I am not having this issue.

what is your version of angular cli? 
I'm trying to use PrimeNG 19.0.8 with Angular CLI 19.2.0 but the problem persist.

**Comment by floreauwe** [comment]
I have same issue with angular 19.1.7 and primeNg 19.0.9.
Any idea how to fix this?

**Comment by chocoboeve** [comment]
I upgraded my project from v18 to v19.0.9, and then I got this problem. Even when I deleted the dependencies primeng and @primeng/themes , I still got this. 
Do we need to build a new project with v19 primeng, and then move the old project to the new ? Does anyone try?

**Comment by mertsincan** [comment]
Could you please share a sample project repo for testing?

**Comment by mertsincan** [comment]
New issue: https://github.com/primefaces/primeng/issues/17833
