### ISSUE TITLE
Component: Table Virtual Scroll does not correctly work with Row Expansion

### ISSUE THREAD

**Issue by jackiems82** [primefaces/primeng#16438]
### Describe the bug

Combining Virtual Scroll with Row Expansion does not always seem to work. 
When the content of the expanded area is quite high, you cannot scroll to the end of the table when there are only a few rows. When there are more rows (e.g. 100) You can correctly scroll to the end, but while scrolling down from the top you will encounter a point where the scroll jumps ahead a couple of rows more than it should. Probably due to swapping out the rows in the DOM.
I need to use lazy loading as there can be quite a number of rows to display. Also the expandable area can have a different height per row.

Here is a stackblitz that shows this: https://stackblitz.com/edit/stackblitz-starters-s7bkee

### Environment

Windows 10

### Angular version

18.0.0

### PrimeNG version

17.18.10

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.15.1

### Steps to reproduce the behavior

First scenario:
1. Expand the first row and scroll to the end with either mouse wheel or by dragging the scroller. 
 => The scroll area jumps up everytime you reach the bottom.

Second scenario:
1. In app.component.ts, line 25, change the array length from 10 to 100.
2. Expand the first row and scroll down. 
=> Around when row with id 11 comes into view, when scrolling further the view will jump several rows down (for me it where 5) when usually it only scrolls around 1 row when using the mouse wheel.

### Expected behavior

I would expect that the scrolling always works without jumping back up or moving too fast ahead, possibly skipping rows that cannot be seen in this case.

**Comment by mark7p** [comment]
Hi @jackiems82 as I recall, this is merged only for V17 because the issue is under V17

> PrimeNG version
> 17.18.10

I haven't looked into v18 and v19 yet as I'm working on other things right now. Hope someone implement this fix for latest versions in the future.

**Comment by jackiems82** [comment]
Thanks @mark7p  for getting back to me. I checked several versions from v17 up until 17.18.15 and unfortunately I could not verify that the issue was fixed for any :(

**Comment by mark7p** [comment]
@jackiems82 I see, thanks for looking into this. Can you create an issue for this? I'll try to create a PR for v19

**Comment by gianluca-moro** [comment]
has this issue been fixed? I am currently facing a similar problem

**Comment by gianluca-moro** [comment]
Still an issue with PrimeNG 19.0.1: https://stackblitz.com/edit/t6j813q4-wg6ppsct?file=src%2Fapp%2Ftable-row-expansion-demo.html

**Comment by mark7p** [comment]
@gianluca-moro @jackiems82 there is a PR #16648 currently on discussion. However, this requires big changes to how `VirtualScroller` aproach content size calculation and need some time to review/optimized. This is a known issue with [primevue](https://primevue.org/) as well.
My bad I closed the issue. Hope the PR will get merged soon.

**Comment by jackiems82** [comment]
@mark7p Thanks for pointing to that other PR and sorry for not getting back here earlier. Let's hope that PR is going to be accepted in the end  :)

**Comment by gianluca-moro** [comment]
It's October 2025, PrimeNG 20 is out and Virtual Scrolling is still a big buggy mess...
