### ISSUE TITLE
Picklist target not update

### ISSUE THREAD

**Issue by LucasAlumni** [primefaces/primeng#18388]
### Describe the bug

In the picklist component, when I add an item to the “target” list, the first element is added correctly. However, when I add another item to the “target” list, targetProduct contains only one element, even though the UI shows two elements in the “target” list.

### Reason for not contributing a PR

- [ ] Lack of time
- [ ] Unsure how to implement the fix/feature
- [ ] Difficulty understanding the codebase
- [ ] Other

### Reproducer

https://stackblitz.com/edit/xammse4a?file=src%2Fapp%2Fpicklist-basic-demo.html,src%2Fapp%2Fpicklist-basic-demo.ts

### Environment

- MacOS (15.5)
- Safari + Chrome

### Angular version

19

### PrimeNG version

v19

### Steps to reproduce the behavior

1 . add source element to target list
2 . add new source element to target list

### Expected behavior

targetProduct must have two elements.

**Comment by gualbertof** [comment]
Confirmed, Same here

**Comment by hkjeffchan** [comment]
Only works on "Ctrl" multi select. If add one by one, only the last one in the target data list.

**Comment by sathyaanarayanan** [comment]
@mehmetcetin01140, wondering if this fix could be merged soon. It's breaking production

**Comment by hkjeffchan** [comment]
I compiled and replace the files in node_modules/primeng/fesm2022 directly

You will need to remove the txt extension as github does not allow mjs and map extension.

[primeng-picklist.mjs.txt](https://github.com/user-attachments/files/20517703/primeng-picklist.mjs.txt)
[primeng-picklist.mjs.map.txt](https://github.com/user-attachments/files/20517702/primeng-picklist.mjs.map.txt)

**Comment by sathyaanarayanan** [comment]
The weird workaround I implemented is as follows: 
Creating a new instance of the array every time the value is updated. 
 
**HTML file:** 

```
    <p-pickList 
        [source]="deselectedColumns" [target]="selectedColumns"
        (onMoveToTarget)="onMoveToTarget($event)"
        (onMoveToSource)="onMoveToSource($event)" 
        (onMoveAllToTarget)="onMoveAllToTarget($event)" 
        (onMoveAllToSource)="onMoveAllToSoaurce($event)"
>
```

**.ts file:**

```

  onMoveAllToTarget(event: any): void {
    this.selectedColumns = [...this.selectedColumns]
    this.deselectedColumns = [...this.deselectedColumns]
  }

  onMoveToTarget(event: any): void {
    this.selectedColumns = [...this.selectedColumns]
    this.deselectedColumns = [...this.deselectedColumns]
  }

  onMoveToSource(event: any): void {
    this.selectedColumns = [...this.selectedColumns]
    this.deselectedColumns = [...this.deselectedColumns]
  }

  onMoveAllToSource(event: any): void {
    this.selectedColumns = [...this.selectedColumns]
    this.deselectedColumns = [...this.deselectedColumns]
  }
```

**Comment by omnight** [comment]
Here is my small workaround (put in the app initialization). 

```
    PickList.prototype.triggerChangeDetection = function () {
        this.selectedItemsSource = [...this.selectedItemsSource];
        this.selectedItemsTarget = [...this.selectedItemsTarget];
    }
```

After each change, the TriggerChangeDetection method seems to create a copy of the target/source lists and then make each subsequent change on the copies instead of the original lists.

**Comment by kuatek** [comment]
Here is my woraround:

HTML: 
```
<p-pickList 
        #pickList
        [source]="deselectedColumns" [target]="selectedColumns"
        (onMoveToTarget)="onMoveToTarget($event)"
        (onMoveToSource)="onMoveToSource($event)" 
        (onMoveAllToTarget)="onMoveAllToTarget($event)" 
        (onMoveAllToSource)="onMoveAllToSoaurce($event)"
>

```

TS:

```
   
@ViewChild('pickList', { static: false }) pickList: PickList;
   
onMoveAllToTarget(event: any): void {
    this.selectedColumns = [...this.pickList.target]
    this.deselectedColumns = [...this.pickList.source]
}

onMoveToTarget(event: any): void {
    this.selectedColumns = [...this.pickList.target]
    this.deselectedColumns = [...this.pickList.source]
}

onMoveToSource(event: any): void {
    this.selectedColumns = [...this.pickList.target]
    this.deselectedColumns = [...this.pickList.source]
}

onMoveAllToSource(event: any): void {
    this.selectedColumns =[...this.pickList.target]
    this.deselectedColumns = [...this.pickList.source]
}

```

**Comment by kheos31** [comment]
Hello there! 

Any news on this issue please? I can't understand how the main goal of the component cannot be achieved currently while there is a PR providing the fix.. 

For information, it seems to be a regression integrated on a minor / patch version of PrimeNG 19.

- PrimeNG version **without bug** : `19.0.9`
- PrimeNG version **with bug** : `19.1.3`

**Comment by andrea-colleoni** [comment]
@kheos31 
sadly 19.0.9 is affected by the filter bug (you can't type spaces in the filter).

**Comment by sathyaanarayanan** [comment]
Are we planning to keep this PR open forever? What's the plan to fix this issue?

**Comment by hkjeffchan** [comment]
> Are we planning to keep this PR open forever? What's the plan to fix this issue?

This is super annoying.......

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/commit/591b02e5aff5f2011b7ff6b939b8e7ba77865cf1

**Comment by hkjeffchan** [comment]
This is still not fixed in v20.2.0.

@cetincakiroglu

**Comment by SamihIsHis** [comment]
Is this going to be merged in v19.x where you originally broke it? I'm stuck with an unusable component after spending over a month updating our large web application from v11 to 19.

I can't tell my QA team they have to regression test all over again because I had to update our entire suite (angular, primeng, ngrx) to v20.

**Comment by SamihIsHis** [comment]
> Here is my woraround:
> 
> HTML:
> 
> ```
> <p-pickList 
>         #pickList
>         [source]="deselectedColumns" [target]="selectedColumns"
>         (onMoveToTarget)="onMoveToTarget($event)"
>         (onMoveToSource)="onMoveToSource($event)" 
>         (onMoveAllToTarget)="onMoveAllToTarget($event)" 
>         (onMoveAllToSource)="onMoveAllToSoaurce($event)"
> >
> ```
> 
> TS:
> 
> ```
>    
> @ViewChild('pickList', { static: false }) pickList: PickList;
>    
> onMoveAllToTarget(event: any): void {
>     this.selectedColumns = [...this.pickList.target]
>     this.deselectedColumns = [...this.pickList.source]
> }
> 
> onMoveToTarget(event: any): void {
>     this.selectedColumns = [...this.pickList.target]
>     this.deselectedColumns = [...this.pickList.source]
> }
> 
> onMoveToSource(event: any): void {
>     this.selectedColumns = [...this.pickList.target]
>     this.deselectedColumns = [...this.pickList.source]
> }
> 
> onMoveAllToSource(event: any): void {
>     this.selectedColumns =[...this.pickList.target]
>     this.deselectedColumns = [...this.pickList.source]
> }
> ```

I was able to simplify this a lot and it still worked. All I needed was:

this.selectedColumns = this.selectedColumns.slice();

Do this on the 4 update events. No need for a view child reference, or different functions for every add/remove/add all/remove all event. Also source columns never changes so doesn't need to be modified.

**Comment by kuatek** [comment]
> > Here is my woraround:
> > HTML:
> > ```
> > <p-pickList 
> >         #pickList
> >         [source]="deselectedColumns" [target]="selectedColumns"
> >         (onMoveToTarget)="onMoveToTarget($event)"
> >         (onMoveToSource)="onMoveToSource($event)" 
> >         (onMoveAllToTarget)="onMoveAllToTarget($event)" 
> >         (onMoveAllToSource)="onMoveAllToSoaurce($event)"
> > >
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > TS:
> > ```
> >    
> > @ViewChild('pickList', { static: false }) pickList: PickList;
> >    
> > onMoveAllToTarget(event: any): void {
> >     this.selectedColumns = [...this.pickList.target]
> >     this.deselectedColumns = [...this.pickList.source]
> > }
> > 
> > onMoveToTarget(event: any): void {
> >     this.selectedColumns = [...this.pickList.target]
> >     this.deselectedColumns = [...this.pickList.source]
> > }
> > 
> > onMoveToSource(event: any): void {
> >     this.selectedColumns = [...this.pickList.target]
> >     this.deselectedColumns = [...this.pickList.source]
> > }
> > 
> > onMoveAllToSource(event: any): void {
> >     this.selectedColumns =[...this.pickList.target]
> >     this.deselectedColumns = [...this.pickList.source]
> > }
> > ```
> 
> I was able to simplify this a lot and it still worked. All I needed was:
> 
> this.selectedColumns = this.selectedColumns.slice();
> 
> Do this on the 4 update events. No need for a view child reference, or different functions for every add/remove/add all/remove all event. Also source columns never changes so doesn't need to be modified.

It is great then! From my end, I am utilizing all the pick list events. I also changed the source in the process. At first, with that approach, I thought it was working, but after manipulating the picklist (using drag and drop), the target was still not updated properly.

**Comment by hkjeffchan** [comment]
> Is this going to be merged in v19.x where you originally broke it? I'm stuck with an unusable component after spending over a month updating our large web application from v11 to 19.
> 
> I can't tell my QA team they have to regression test all over again because I had to update our entire suite (angular, primeng, ngrx) to v20.

https://github.com/primefaces/primeng/issues/18388#issuecomment-2921649750
Use these if you are on v19. I fixed it by moving them to signals but PR was not merged. May do so in v20 if prime team thinks it is a good approach to do so.
