### ISSUE TITLE
Autocomplete input field not cleared or reset

### ISSUE THREAD

**Issue by thirumalai-kc** [primefaces/primeng#3479]
**Current behavior**
p-autocomplete input field is not cleared/reset to null if I dont select an option from suggestion

**Expected behavior**
Input field should be reset to null

**Minimal reproduction of the problem with instructions**
<p-autoComplete placeholder="Start typing name to see suggestions" formControlName="customerRequest" [suggestions]="customerResults" (completeMethod)="searchCustomer('customer_name', $event.query)" minLength="3" field="accountName" (onSelect)="setCustomerRequest($event)">

Start type 'abc'
Do not choose a value from the option
Perform clear (Here using clear button which invoke method to make customerRequest null)

Result: customerRequest (model) set to null but the input field is not cleared/reset.

Expected: Field should be reset to null.

If I select some value from the option and clear, field is reset to null. Please address this issue.

* **Angular version:** 2.0.X

* **PrimeNG version:** 4.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by mmlitvin** [comment]
I see this exact problem as well. Upvoting for a fix.

**Comment by pageii** [comment]
Upvoting for a fix as well.

**Comment by cagataycivici** [comment]
Tracked at #3479

**Comment by huineng** [comment]
you referenced same ticket number ?  where is this tracked ?
and there's no 4.1.4 milestone , you refer to 4.2.0 rc1 ?
thanks

**Comment by kavoos** [comment]
@cagataycivici fixed in v4.2.0 if `[multiple]="false"` but not if you use `[multiple]="true"`

**Comment by JamboBuenna** [comment]
Bump :-)
Doesn't seem to be fixed if not if you use [multiple]="true". 
Has anyone got a work-around, even changing the dom element?

**Comment by Darnoj** [comment]
@cagataycivici Issue still exists when you manually clear the input.
Type 'a' / Select an option / FormModel updated / clear the input / focus out / the FormModel still contains the old selection.
Workaround : use the onClear to manually set the formControl value to null...

**Comment by Faqtt0** [comment]
Still exists "primeng": "^6.1.4.
I've two "autocomplete" and i clear manually. One clear and the another in screen continue with value. Even when binding variable is null

**Comment by K-R0N** [comment]
What was the fix for this? I'm still experiencing this issue and this is an old ticket that was closed.
"primeng": "^10.0.3"
