### ISSUE TITLE
DataTable reset() not updating pagination display

### ISSUE THREAD

**Issue by bproctor-threatconnect** [primefaces/primeng#474]
When calling `reset()` on the dataTable (i.e. after changing the data externally), the displayed pagination at the bottom of the table does not update properly. The table correctly goes back to viewing the data from page 1, but the page links at the bottom do not update, other than to remove the `ui-state-active` class from the previously-active page.

**Comment by mkemmerling** [comment]
The following workaround works for me: Calling `updatePaginator()` manually on the dataTable after calling `reset()`.

**Comment by bproctor-threatconnect** [comment]
I'm assuming that this issue has been resolved in the many releases since I opened it. They were still in like beta 2 when I posted this(almost a year ago).

**Comment by bproctor-threatconnect** [comment]
Didn't mean to close the issue. As it may still be present.

@mkemmerling that workaround didn't work when I originally opened this issue.

**Comment by mkemmerling** [comment]
The problem occurred for me in 4.0.0-rc.3.

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by dileepkeeppalli** [comment]
Still facing this issue. I am using PrimeNG table with angular tree.
If I am in the second page of my PrimeNG data table and switching the tree node and again come back to same view pagination is not reseting to 1st page
