### ISSUE TITLE
Dialog issue , onHide not triggered 

### ISSUE THREAD

**Issue by victos** [primefaces/primeng#6277]
primeng version 6.1.0
angular version 6.1.1
When use the ngIf and visible at the same time and use the same variable, the event onHide not triggered.
https://stackblitz.com/edit/github-njvgs6?file=src/app/app.component.html

**Comment by JacobSiegle** [comment]
I'm assuming in your actual code example the visible var and *ngIf var are not the same. In this scenario can you not just remove the *ngIf and change visible to [(visible)]="var1 && var2"? I'm not sure onHide should be called with *ngIf because it isn't hidden it's destroyed.

**Comment by yigitfindikli** [comment]
Why do you want it? Already visible property do that.

**Comment by victos** [comment]
I want to remove the dialog from the dom tree. That works in the previous version (>- 6.0.0)

**Comment by yigitfindikli** [comment]
Maybe you can use visibleChange property like that 
<p-dialog [(visible)]="showWithNgIf" *ngIf="showWithNgIf" (visibleChange)="onHide()">
	this is the dialog
</p-dialog>

**Comment by victos** [comment]
I saw the attribute in the source code, but it didn't appeared in the document, I don't know if it'll be removed in the future.

**Comment by cagataycivici** [comment]
Fixed via #6286

**Comment by victos** [comment]
@cagataycivici 
This issue comes back.

**Comment by crissty** [comment]
Yes, this issue is happening in 6.1.4 version of primeng

**Comment by stephanie-dm** [comment]
This issue was also mentioned in #6925 and seems still present in PrimeNG 8...
