### ISSUE TITLE
Only inside p-overlayPanel, p-calendar has month/year navigation problem

### ISSUE THREAD

**Issue by darius-iko** [primefaces/primeng#7693]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-mkrr8t

**Current behavior**
Clicking on the month navigation button either forward or backward will cause overlay panel behind and the calendar itself to close. (This issue does not exist on PrimeNG version 7.0.4 and older).

**Expected behavior**
Calendar should navigate to next/previous month instead of closing overlay component and the calendar itself.

**Minimal reproduction of the problem with instructions**
Step to reproduce:
1. Open URL https://stackblitz.com/edit/github-mkrr8t
2. Click on the button "Open Overlay"
![image](https://user-images.githubusercontent.com/8023913/57848400-5f476a80-780b-11e9-9441-20a247ba1909.png)
3. Click on the calendar button to open the calendar overlay.
![image](https://user-images.githubusercontent.com/8023913/57848535-b64d3f80-780b-11e9-862e-1a0da565d148.png)
4. Click on the month navigation button either forward or backward will cause overlay panel behind and the calendar itself to close.
![image](https://user-images.githubusercontent.com/8023913/57848648-f90f1780-780b-11e9-830e-2669eb53d754.png)

**What is the motivation / use case for changing the behavior?**
The calendar inside an overlay panel can be used as complex filter for a column in the turbo table, e.g: to filter with date range and created person name in a column.

**Please tell us about your environment:**
Windows 8.1, VS Code

* **Angular version:** 7.1.0

* **PrimeNG version:** 7.1.2

* **Browser:** all
 
* **Language:** TypeScript

**Suggestion to fix**: 
Please use setTimeout to delay modifying the property in the calendar component when navigating forward or backward. This is to make sure that the navigation button will not be replaced directly that will cause the overlay panel behind to mistakenly assume the navigation button is not descendant of overlay panel while listening on document click event that hide the panel.
![image](https://user-images.githubusercontent.com/8023913/57849231-58215c00-780d-11e9-8174-30c42fc4ddec.png)

**Comment by redouane20063** [comment]
Is this problem fixed, I still have the same problem how to fix this

**Comment by mertsincan** [comment]
Thanks a lot for the all PR! But, I implemented a different solution.

Best Regards,

**Comment by imrahamed** [comment]
@mertsincan what is that different solution?
can you provide a workaround  please

**Comment by comlabmohan** [comment]
> Thanks a lot for the all PR! But, I implemented a different solution.
> 
> Best Regards,

Hi @mertsincan  I am using  the primeng 7.1.3 version still overlay panel is closed when navigating use the p-calaendar naviagtion buttons can you please share the workaround which you tried that will be help full for me.

**Comment by nehashahkedia** [comment]
This issue still persists in version 16.9.1 . Any plan for permanent fix around this.

**Comment by vamsidhar1999** [comment]
I'm still facing the same issue in primeng 16.9.1. Is there any workaround or fix for this ?

**Comment by Adrigondo** [comment]
@nehashahkedia @vamsidhar1999, have you tried version 17.3.1? We had that problem in a project, and updating everything to Angular 17 (and consequently, primeng) worked fine again.

**Comment by nehashahkedia** [comment]
Using version 16 which is the LTS. Version 17 has come with LTS?

**Comment by Adrigondo** [comment]
> Using version 16 which is the LTS. Version 17 has come with LTS?

No, it doesn't have a LTS version yet.
